### ISSUE TITLE
3D simulation result visualization

### ISSUE THREAD

**Issue by veronikarichter** [BIM2SIM/bim2sim#509]
Adds a 3D simulation result visualization based on #387. 

- [x] Implement simple floorplan visualization
- [ ] Add option in settings to export floorplan visualization

**Comment by DaJansenGit** [comment]
@veronikarichter this is already solved and the floorplan is created by default currently. Do we really need a specific `sim_setting` for this? My suggestion would be to have a generel `sim_setting` like `plot_results` which is a list of results to be plotted and exported. What do you think?

**Comment by veronikarichter** [comment]
Yes, this issue has been resolved already.
