### ISSUE TITLE
update to MSL 4.0 for export

### ISSUE THREAD

**Issue by DaJansenGit** [BIM2SIM/bim2sim#520]
Current template in `\bim2sim\assets\templates\modelica\tmplModel.txt` uses `  import SI = Modelica.SIunits;` which is not working with MSL 4.0 but only MSL <= 3.2.3. As AixLib uses MSL 4.0 we need to update this. If HKESim still uses MSL 3.2.3 we need to add the option for multiple templates, as they are currently fixed. @PooyanJahangiri and @sfreund1: which MSL version are you using?

**Comment by sfreund1** [comment]
HKESim now uses MSL 4.0, so seperate templates are not necessary.

**Comment by DaJansenGit** [comment]
closed in dev
