### ISSUE TITLE
Error in 'setup.py install': Parsing Issue with Git Dependency URL

### ISSUE THREAD

**Issue by farisabit** [BIM2SIM/bim2sim#552]
**Issue:**
When trying to install the bim2sim module using the setup.py file, I encountered a parsing error related to the Git dependency URL specified in the install_requires field.

**Steps to Reproduce:**

Clone the bim2sim repository.
Navigate to the bim2sim project directory.
Attempt to install the package using python setup.py install.

**Error Message:**

error in bim2sim setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'"git+htt'": Expected W:(0-9A-Za-z)

**Additional info:**
Python 3.9.16

**Get-around:**
I just deleted that line bc such link can't be found. However, I couldn't still run BIM2SIM when I ran 'python bim2sim -h'. 

Thank you for your time and support in resolving this issue.

**Comment by Cudok** [comment]
@farisabit which OS you used when this error occurs?

**Comment by farisabit** [comment]
macOS Ventura 13.5 2 on M2.

**Comment by Cudok** [comment]
I have the same error with the OS: ubuntu 22.04 (Pop!OS)

**Comment by Cudok** [comment]
There is a new Installation guide: [Installation guide](https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/development/docs/installation.html)
