### ISSUE TITLE
https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/main/docs/overview.html error 404

### ISSUE THREAD

**Issue by Cudok** [BIM2SIM/bim2sim#576]
on page https://ebc-tools.eonerc.rwth-aachen.de/bim2sim

click on "hier" 

the link https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/main/docs/overview.html shows error 404

**Comment by DaJansenGit** [comment]
link works again, anyway documentation was moved to github pages. I already asked our webmaster team to update the link. I will close this now as the old link works again and in the next days the new link should be there.
