### ISSUE TITLE
clarify parameter names in enrich use condition

### ISSUE THREAD

**Issue by veronikarichter** [BIM2SIM/bim2sim#587]
Custom file paths can be defined for the use conditions that should be used in the project (prj_use_conditions), as well as for a mapping table of zone names and zone usages for this specific project (prj_custom_usages). However, in the [enrich_use_cond.py](https://github.com/BIM2SIM/bim2sim/blob/27969e1f7b6d293d684c45260e17f2c8021814e2/bim2sim/tasks/bps/enrich_use_cond.py#L28), the mapping of these file paths to parameter names is misleading.

**Comment by DaJansenGit** [comment]
closed through #592
