### ISSUE TITLE
create pyproject.toml

### ISSUE THREAD

**Issue by Cudok** [BIM2SIM/bim2sim#651]
Create a pyproject.toml for the whole bim2sim framework.

The pyproject.toml should include:
- [x] build system
- [x] project meta data
  - [x] general dependencies
  - [x] project infos
- [x] dev dependencies
  - [x] pylint 
- [x] test dependencies
- [x] test setup

**Comment by Cudok** [comment]
## actual situation
- 1st version of the pyproject.toml added
  - @DaJansenGit pls check, especially the authors
- sphinx docu was adapted
  - @Cudok  done a test by using the instructions to setup a new repo and env
- there are a lot of warings when buiding the shinx docu and also not all tests are running without failtures
  - @DaJansenGit we have to check this before make a Pullrequest

**Comment by DaJansenGit** [comment]
this is closed and will be continued in #682
